# Site settings
title: Darko
email: y
description: "A minimlistic Dark themed jekyll theme"
baseurl: ""
url: "http://yourdomain.com"
twitter: jekyllrb
github:  jekyll
linkedin:
facebook:
gmail:


# Build settings
markdown: kramdown
permalink: pretty
