# Site settings
title: Darko
email: y
description: "A minimlistic Dark themed jekyll theme"
baseurl: ""
url: "http://yourdomain.com"
twitter: "ayush0016"
github: "ayush1997"
linkedin: "ayushsingh97"
facebook: "ayush.coder"
gmail: ""
topic: [Home,About,DownloadTheme]

# Build settings
markdown: kramdown
permalink: pretty
